package com.example.vinyl.ui.onboarding

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Refresh
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.draw.drawWithContent
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.vinyl.data.onboarding.AvatarOption
import com.example.vinyl.ui.theme.VinylPalette

/**
 * Page 1. The username is generated by the database when the account is created
 * (`generate_username()`, see DATABASE.md) and is never typed by the user. They can ask for
 * another one with "Try another name" while onboarding is open; after that it is fixed. The
 * other choice on this page is the icon.
 *
 * Thin wrapper around [UsernameAvatarContent] — same split as `LocationGateScreen`/
 * `LocationGateContent` — so the content composable can be previewed with plain state instead of
 * a real [OnboardingViewModel].
 */
@Composable
fun UsernameAvatarPage(
    viewModel: OnboardingViewModel,
    onNext: () -> Unit,
    modifier: Modifier = Modifier,
) {
    val state by viewModel.uiState.collectAsState()
    UsernameAvatarContent(
        state = state,
        onSelectAvatar = viewModel::selectAvatar,
        onRerollName = viewModel::rerollUsername,
        onNext = { viewModel.saveAvatar(onSaved = onNext) },
        modifier = modifier,
    )
}

@Composable
private fun UsernameAvatarContent(
    state: OnboardingUiState,
    onSelectAvatar: (String) -> Unit,
    onRerollName: () -> Unit,
    onNext: () -> Unit,
    modifier: Modifier = Modifier,
) {
    Column(
        modifier = modifier
            .fillMaxSize()
            .padding(horizontal = 32.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
    ) {
        Spacer(Modifier.height(12.dp))


        Text(
            text = "You're known here as",
            color = VinylPalette.TextMuted,
            fontSize = 15.sp,
            textAlign = TextAlign.Center,
            modifier = Modifier.padding(top = 20.dp),
        )

        // The button's width. An empty slot of the same width on the left keeps the name pill
        // centred on screen while the button sits at the right end.
        val slot = 56.dp

        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(top = 12.dp),
            verticalAlignment = Alignment.CenterVertically,
        ) {
            Spacer(Modifier.size(slot))

            // Fixed size whatever the name is: only the text inside shrinks to fit.
            Box(
                modifier = Modifier
                    .weight(1f)
                    .height(64.dp)
                    .clip(RoundedCornerShape(50))
                    .border(
                        width = 1.dp,
                        color = VinylPalette.TealAccent,
                        shape = RoundedCornerShape(50),
                    )
                    .padding(horizontal = 16.dp),
                contentAlignment = Alignment.Center,
            ) {
                FitText(
                    text = if (state.isLoadingProfile) "…" else state.username,
                    color = VinylPalette.TealAccent,
                    maxSp = 30f,
                    minSp = 14f,
                )
            }

            // Fixed size, fixed spot: right end of the row, vertically centred on the name.
            IconButton(
                onClick = onRerollName,
                enabled = !state.isLoadingProfile && !state.isRerollingName,
                modifier = Modifier.size(slot),
            ) {
                if (state.isRerollingName) {
                    CircularProgressIndicator(
                        color = VinylPalette.TextMuted,
                        strokeWidth = 3.dp,
                        modifier = Modifier.size(28.dp),
                    )
                } else {
                    Icon(
                        imageVector = Icons.Filled.Refresh,
                        contentDescription = "Try another name",
                        tint = VinylPalette.TextMuted,
                        modifier = Modifier.size(32.dp),
                    )
                }
            }
        }

        Text(
            text = "Pick your profile icon",
            color = VinylPalette.TextPrimary,
            fontSize = 33.sp,
            fontWeight = FontWeight.Medium,
            textAlign = TextAlign.Center,
            lineHeight = 50.sp,
            modifier = Modifier.padding(top = 50.dp)
        )


        // Fills the whole space between the intro text and the button — no dead gap regardless
        // of avatar count or screen height, and the icons stay centered within it.
        Box(
            modifier = Modifier
                .weight(1f)
                .fillMaxWidth(),
            contentAlignment = Alignment.Center,
        ) {
            if (state.isLoadingProfile) {
                CircularProgressIndicator(color = VinylPalette.TealAccent)
            } else {
                Column(
                    verticalArrangement = Arrangement.spacedBy(20.dp),
                    horizontalAlignment = Alignment.CenterHorizontally,
                ) {
                    state.avatarOptions.chunked(3).forEach { row ->
                        Row(horizontalArrangement = Arrangement.spacedBy(20.dp)) {
                            row.forEach { avatar ->
                                AvatarIcon(
                                    avatar = avatar,
                                    selected = avatar.slug == state.selectedAvatarSlug,
                                    onClick = { onSelectAvatar(avatar.slug) },
                                )
                            }
                        }
                    }
                }
            }
        }

        state.errorMessage?.let {
            Text(it, color = VinylPalette.TealAccent, fontSize = 13.sp, textAlign = TextAlign.Center)
        }

        Button(
            onClick = onNext,
            // With no icons on offer (the avatars table starts empty) there is nothing to pick, so don't block.
            enabled = (state.selectedAvatarSlug != null || state.avatarOptions.isEmpty()) && !state.isSaving,
            modifier = Modifier
                .fillMaxWidth()
                .height(112.dp)
                .padding(top = 8.dp, bottom = 55.dp),
            shape = RoundedCornerShape(50),
            colors = ButtonDefaults.buttonColors(
                containerColor = VinylPalette.TealAccent,
                contentColor = VinylPalette.Background,
            ),
        ) {
            Text(
                text = if (state.isSaving) "Saving…" else "Next",
                fontWeight = FontWeight.Medium,
                fontSize = 15.sp,
            )
        }
    }
}

/**
 * One-line text that starts at [maxSp] and shrinks until it fits the space it's given, down to
 * [minSp]. Hidden until it has settled, so the shrinking never flashes on screen.
 */
@Composable
private fun FitText(
    text: String,
    color: Color,
    maxSp: Float,
    minSp: Float,
    modifier: Modifier = Modifier,
) {
    // Both restart whenever the text changes, e.g. after "Try another name".
    var sizeSp by remember(text) { mutableStateOf(maxSp) }
    var readyToDraw by remember(text) { mutableStateOf(false) }

    Text(
        text = text,
        color = color,
        fontSize = sizeSp.sp,
        fontWeight = FontWeight.Medium,
        textAlign = TextAlign.Center,
        maxLines = 1,
        softWrap = false,
        onTextLayout = { result ->
            if (result.didOverflowWidth && sizeSp > minSp) {
                sizeSp = maxOf(minSp, sizeSp * 0.92f)
            } else {
                readyToDraw = true
            }
        },
        modifier = modifier.drawWithContent { if (readyToDraw) drawContent() },
    )
}

/**
 * Placeholder rendering: a big plain circle with the option's initials. Swap for an image loader
 * (e.g. Coil's AsyncImage) on `avatar.url` once the real icon set exists — keep the 96dp size, it's
 * deliberately large per the "zoomed in" direction on this page.
 */
@Composable
private fun AvatarIcon(avatar: AvatarOption, selected: Boolean, onClick: () -> Unit) {
    Box(
        modifier = Modifier
            .size(96.dp)
            .clip(CircleShape)
            .background(VinylPalette.TextMuted.copy(alpha = 0.15f))
            .border(
                width = if (selected) 3.dp else 1.dp,
                color = if (selected) VinylPalette.TealAccent else VinylPalette.TextMuted.copy(alpha = 0.3f),
                shape = CircleShape,
            )
            .clickable(onClick = onClick),
        contentAlignment = Alignment.Center,
    ) {
        Text(
            text = avatar.slug.takeLast(2),
            color = VinylPalette.TextPrimary,
            fontWeight = FontWeight.Medium,
            fontSize = 24.sp,
        )
    }
}

@Preview(showBackground = true, backgroundColor = 0xFF0D0D0D, heightDp = 800)
@Composable
private fun UsernameAvatarContentPreview() {
    UsernameAvatarContent(
        state = OnboardingUiState(
            isLoadingProfile = false,
            username = "Happy Giraffe",
            avatarOptions = (1..8).map { n ->
                AvatarOption(slug = "avatar_%02d".format(n), url = "placeholder", sortOrder = n)
            },
            selectedAvatarSlug = "avatar_04",
        ),
        onSelectAvatar = {},
        onRerollName = {},
        onNext = {},
    )
}

/** Longest possible generated name (8-letter adjective, 9-letter animal, 4-digit suffix). */
@Preview(showBackground = true, backgroundColor = 0xFF0D0D0D, heightDp = 800)
@Composable
private fun UsernameAvatarLongNamePreview() {
    UsernameAvatarContent(
        state = OnboardingUiState(
            isLoadingProfile = false,
            username = "Tropical Chameleon 4821",
            avatarOptions = (1..8).map { n ->
                AvatarOption(slug = "avatar_%02d".format(n), url = "placeholder", sortOrder = n)
            },
            selectedAvatarSlug = "avatar_04",
        ),
        onSelectAvatar = {},
        onRerollName = {},
        onNext = {},
    )
}