-- =============================================================================
-- Vinyl — 0010: server-generated usernames
--
-- Every profile gets a unique "Adjective Animal" username ("Happy Giraffe",
-- "Sleepy Tiger") generated by the database. The client never supplies it, it is
-- unique case-insensitively, and it can be re-rolled during onboarding only.
--
-- HOW THIS FITS DATABASE.md
--
--   * The name goes in a NEW column, profiles.username. display_name and
--     avatar_url keep holding the private Google identity, exactly as documented;
--     this file does not read, change or null them, and does not touch
--     handle_new_user(). Whether the Google identity is still worth storing is
--     the team's separate question.
--   * profiles is owner-only under RLS, so a username is visible to its owner and
--     nobody else — same as every other profile column. Nothing here adds a
--     policy, an RPC return column or a room_card field that could show it.
--   * Avatars are unaffected: keep public.avatars / profiles.avatar_slug.
--
-- Idempotent: safe to re-run (the backfill only touches rows with no username).
-- =============================================================================


-- -----------------------------------------------------------------------------
-- 1. The column
--
-- Nullable until the backfill has run, then NOT NULL (section 5).
-- -----------------------------------------------------------------------------

alter table public.profiles
  add column if not exists username text;

comment on column public.profiles.username is
  'Server-generated "Adjective Animal" alias, unique (case-insensitive). Written only by the database; the client can only call reroll_username() during onboarding. Private to the owner.';


-- -----------------------------------------------------------------------------
-- 2. The generator
--
-- SECURITY DEFINER because the uniqueness check has to see EVERY profile, and RLS
-- would otherwise show a signed-in caller only their own row.
--
-- The advisory lock serialises generation. It is held until the surrounding
-- transaction commits, i.e. until the row the name goes into exists, so two
-- signups at the same instant cannot both pick "Happy Giraffe". Signups are rare
-- enough that queueing them costs nothing.
--
-- Capacity: 60 x 60 = 3600 combinations. After 25 failed random picks a 4-digit
-- number is appended ("Happy Giraffe 4821"), so signup can never fail because the
-- pool is crowded. That only starts happening at roughly 85% full (~3000 users):
-- widen the lists before then if you would rather never show numbers.
-- -----------------------------------------------------------------------------

create or replace function public.generate_username()
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  adjectives text[] := array[
    'Happy', 'Sleepy', 'Sunny', 'Jolly', 'Dreamy', 'Breezy', 'Groovy', 'Cozy',
    'Mellow', 'Cheeky', 'Bouncy', 'Fuzzy', 'Giddy', 'Snazzy', 'Zesty', 'Peppy',
    'Sparkly', 'Lazy', 'Witty', 'Gentle', 'Plucky', 'Bubbly', 'Dizzy', 'Funky',
    'Merry', 'Quirky', 'Rosy', 'Sassy', 'Twinkly', 'Wobbly', 'Cuddly', 'Dapper',
    'Chirpy', 'Fluffy', 'Glowy', 'Goofy', 'Snuggly', 'Speedy', 'Swirly', 'Toasty',
    'Zippy', 'Jazzy', 'Nifty', 'Perky', 'Silly', 'Shiny', 'Silky', 'Spunky',
    'Wiggly', 'Frosty', 'Sugary', 'Tropical', 'Sleek', 'Lucky', 'Cheery', 'Snappy',
    'Peachy', 'Minty', 'Fizzy', 'Starry'
  ];
  animals text[] := array[
    'Giraffe', 'Tiger', 'Panda', 'Koala', 'Otter', 'Flamingo', 'Toucan', 'Llama',
    'Penguin', 'Sloth', 'Lemur', 'Parrot', 'Gecko', 'Dolphin', 'Hedgehog',
    'Walrus', 'Zebra', 'Capybara', 'Meerkat', 'Quokka', 'Puffin', 'Narwhal',
    'Octopus', 'Raccoon', 'Bunny', 'Fox', 'Owl', 'Seal', 'Camel', 'Iguana',
    'Alpaca', 'Badger', 'Beaver', 'Chameleon', 'Cheetah', 'Corgi', 'Crab',
    'Duckling', 'Falcon', 'Ferret', 'Gazelle', 'Hamster', 'Hippo', 'Jaguar',
    'Kitten', 'Lynx', 'Manatee', 'Moose', 'Ocelot', 'Pangolin', 'Peacock',
    'Piglet', 'Platypus', 'Pony', 'Rhino', 'Starfish', 'Turtle', 'Wombat', 'Yak',
    'Kiwi'
  ];
  v_name text;
  v_try  integer := 0;
begin
  perform pg_advisory_xact_lock(hashtext('vinyl.username'));

  loop
    v_try := v_try + 1;

    v_name := adjectives[1 + floor(random() * array_length(adjectives, 1))::int]
           || ' '
           || animals[1 + floor(random() * array_length(animals, 1))::int];

    if v_try > 25 then
      v_name := v_name || ' ' || (1000 + floor(random() * 9000))::int;
    end if;

    exit when not exists (
      select 1 from public.profiles p where lower(p.username) = lower(v_name)
    );
  end loop;

  return v_name;
end;
$$;


-- -----------------------------------------------------------------------------
-- 3. Assign on insert, whatever the insert path
--
-- profiles_insert_own lets a signed-in client insert its own profile row, so the
-- name is assigned in a BEFORE INSERT trigger on profiles and always overwrites
-- whatever was supplied. handle_new_user() is unchanged and needs no edit: its
-- INSERT fires this trigger like any other.
-- -----------------------------------------------------------------------------

create or replace function public.profiles_assign_username()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.username := public.generate_username();
  return new;
end;
$$;

drop trigger if exists profiles_assign_username on public.profiles;
create trigger profiles_assign_username
  before insert on public.profiles
  for each row execute function public.profiles_assign_username();


-- -----------------------------------------------------------------------------
-- 4. Backfill existing accounts
--
-- One row per statement: a single UPDATE cannot see its own earlier rows and
-- could hand out the same name twice. Only rows without a username are touched,
-- which is what makes a re-run harmless.
-- -----------------------------------------------------------------------------

do $$
declare
  r record;
begin
  for r in select id from public.profiles where username is null order by created_at loop
    update public.profiles
       set username = public.generate_username()
     where id = r.id;
  end loop;
end $$;


-- -----------------------------------------------------------------------------
-- 5. Guarantees
-- -----------------------------------------------------------------------------

alter table public.profiles alter column username set not null;

create unique index if not exists profiles_username_uniq
  on public.profiles (lower(username));


-- -----------------------------------------------------------------------------
-- 6. The client cannot rename itself, or reopen onboarding
--
-- profiles_update_own would otherwise let a signed-in client write any column.
-- Both guards test current_user: a direct client update runs as 'authenticated',
-- while reroll_username() below (SECURITY DEFINER), the SQL editor and migrations
-- run as the owner and are let through.
--
-- The second guard matters because reroll_username() only works while
-- onboarding_completed is false; without it a client could flip the flag back and
-- reroll forever. Reopening onboarding is still possible from the SQL editor.
-- -----------------------------------------------------------------------------

create or replace function public.profiles_lock_username()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.username is distinct from old.username
     and current_user in ('authenticated', 'anon') then
    raise exception 'username cannot be changed' using errcode = '42501';
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_lock_username on public.profiles;
create trigger profiles_lock_username
  before update of username on public.profiles
  for each row execute function public.profiles_lock_username();

create or replace function public.profiles_onboarding_one_way()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if old.onboarding_completed and not new.onboarding_completed
     and current_user in ('authenticated', 'anon') then
    raise exception 'onboarding cannot be reopened' using errcode = '42501';
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_onboarding_one_way on public.profiles;
create trigger profiles_onboarding_one_way
  before update of onboarding_completed on public.profiles
  for each row execute function public.profiles_onboarding_one_way();


-- -----------------------------------------------------------------------------
-- 7. reroll_username() — the "I don't like this name" button
--
-- Only while onboarding is unfinished, so the name is a free choice at the start
-- and fixed afterwards. Returns the new name; the old one goes back in the pool.
-- Unlimited rerolls are allowed on purpose: it is one cheap write and a user can
-- only ever hold one name at a time. Add a counter column if that changes.
-- -----------------------------------------------------------------------------

create or replace function public.reroll_username()
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid  uuid := auth.uid();
  v_name text;
begin
  if v_uid is null then
    raise exception 'not authenticated' using errcode = '28000';
  end if;

  update public.profiles
     set username = public.generate_username()
   where id = v_uid
     and not onboarding_completed
  returning username into v_name;

  if v_name is null then
    raise exception 'your username can no longer be changed' using errcode = '42501';
  end if;

  return v_name;
end;
$$;


-- -----------------------------------------------------------------------------
-- 8. Privileges
--
-- PostgREST exposes every function in public that a role can execute, and
-- Supabase grants new functions to anon and authenticated by default. Only
-- reroll_username() is meant to be callable, and only when signed in. The rest
-- are internal: trigger functions need no EXECUTE for the role that fires them.
-- -----------------------------------------------------------------------------

revoke execute on function public.generate_username()            from public, anon, authenticated;
revoke execute on function public.profiles_assign_username()     from public, anon, authenticated;
revoke execute on function public.profiles_lock_username()       from public, anon, authenticated;
revoke execute on function public.profiles_onboarding_one_way()  from public, anon, authenticated;

revoke execute on function public.reroll_username() from public, anon;
grant  execute on function public.reroll_username() to authenticated;


-- -----------------------------------------------------------------------------
-- 9. retire the pick-from-a-list pool

alter table public.profiles drop column if exists username_slug;
drop table  if exists public.usernames;
-- -----------------------------------------------------------------------------